### ISSUE TITLE
Remove @group from description

### ISSUE THREAD

**Issue by JoshuaDoshua** [Mikhus/gulp-help-doc#10]
Seems a bit redundant to include the @group in the description as well.
Could this be removed from the output description?

**Comment by Morishiri** [comment]
Hi,
I'm not this repository maintainer, but I think you are doing something wrong as I don't have this problem.
With gulpfile like this:
```
const gulp = require('gulp');
const usage = require('gulp-help-doc');

/**
 * Prints this help usage
 *
 * @task {help}
 * @group {Misc}
 * @order {11}
 */
gulp.task('help', function() { return usage(gulp); });

/**
 * build app
 *
 * @task {build}
 * @group {Main cycle}
 * @order {21}
 */
gulp.task('build', function() { console.log('build task!'); });
```
While running `gulp help` it displays:
```
[18:42:40] Using gulpfile ~/Repositories/gulp-help-doc-test/gulpfile.js
[18:42:40] Starting 'help'...
Usage: gulp [task] [options]
Tasks:
 Misc
    help            Prints this help usage

 Main cycle
    build           build app

[18:42:40] Finished 'help' after 3.63 ms
```
So for me everything looks ok. Maybe you want to provide your example gulpfile so I caould help you find the issue?

**Comment by JoshuaDoshua** [comment]
AH!
I just noticed I had the `@group` _before_ the `@task` annotations.
moving them after fixed.

Thanks for helping!
